from enum import Enum

class SessionStatus(Enum):
    INITIALIZED = "INITIALIZED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ENDED_WIN = "ENDED_WIN"
    ENDED_LOSS = "ENDED_LOSS"
    ENDED_MANUAL = "ENDED_MANUAL"
    ENDED_TIMEOUT = "ENDED_TIMEOUT"

class SessionEndReason(Enum):
    UPPER_LIMIT = "UPPER_LIMIT_REACHED"
    LOWER_LIMIT = "LOWER_LIMIT_REACHED"
    MANUAL = "MANUAL_EXIT"
    TIMEOUT = "MAX_DURATION_REACHED"
    MAX_GAMES = "MAX_GAMES_REACHED"

class OddsType(Enum):
    FIXED = "FIXED"
    PROBABILITY_BASED = "PROBABILITY_BASED"
    AMERICAN = "AMERICAN"
    DECIMAL = "DECIMAL"

class TransactionType(Enum):
    INITIAL_STAKE = "INITIAL_STAKE"
    BET_PLACED = "BET_PLACED"
    BET_WIN = "BET_WIN"
    BET_LOSS = "BET_LOSS"
    DEPOSIT = "DEPOSIT"
    WITHDRAWAL = "WITHDRAWAL"
    ADJUSTMENT = "ADJUSTMENT"
    RESET = "RESET"

class ValidationErrorType(Enum):
    STAKE_ERROR = "STAKE_ERROR"
    BET_ERROR = "BET_ERROR"
    LIMIT_ERROR = "LIMIT_ERROR"
    PROBABILITY_ERROR = "PROBABILITY_ERROR"
    NUMERIC_ERROR = "NUMERIC_ERROR"
    RANGE_ERROR = "RANGE_ERROR"
    NULL_ERROR = "NULL_ERROR"