from enum import Enum

class SessionStatus(Enum):
    INITIALIZED = "INITIALIZED"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ENDED_WIN = "ENDED_WIN"
    ENDED_LOSS = "ENDED_LOSS"
    ENDED_MANUAL = "ENDED_MANUAL"
    ENDED_TIMEOUT = "ENDED_TIMEOUT"

class SessionEndReason(Enum):
    UPPER_LIMIT = "UPPER_LIMIT_REACHED"
    LOWER_LIMIT = "LOWER_LIMIT_REACHED"
    MANUAL = "MANUAL_EXIT"
    TIMEOUT = "MAX_DURATION_REACHED"
    MAX_GAMES = "MAX_GAMES_REACHED"